apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
 name: fluxchallenge-deploy
 namespace: flux-system
spec:
 interval: 1m0s
 path: ./marco
 prune: true
 sourceRef:
  kind: GitRepository
  name: fluxchallenge